data:
  dataset_names: [
    # "m4_daily",
    # "m4_hourly",
    # "m4_monthly",
    # "m4_yearly",
    # "monash_australian_electricity",
    # "taxi_30min",
    # "monash_traffic",
    # "monash_kdd_cup_2018",
    # "m5",
    # "mexico_city_bikes",
    "exchange_rate",
    # "monash_car_parts",
    # "monash_covid_deaths",
    # "monash_electricity_hourly",
    # "monash_fred_md",
    # "monash_hospital",
    # "monash_m1_monthly",
    # "monash_m1_quarterly",
    # "monash_m1_yearly",
    # "monash_m3_monthly",
    # "monash_m3_quarterly",
    # "monash_m3_yearly",
    # "monash_nn5_weekly",
    # "uber_tlc_daily",
    # "uber_tlc_hourly",
    # "wind_farms_hourly",
    # "wind_farms_daily",
    # "dominick",
    # "electricity_15min",
    # "solar_1h"
  ]
  batch_size: 1024
  image_size: 64
  normalize: true
  num_workers: 0 # Set to 0 on Windows to avoid pykan pickling errors
  context_length: 384
  prediction_length: 96

model:
  hidden_dim: 128
  projection_dim: 64
  lr: 0.001
  temperature: 0.07
  encoder_checkpoint: "outputs/lightning_logs/version_0/checkpoints/last.ckpt" # Update this after main.py run

training:
  max_epochs: 10
  precision: "16-mixed"
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  default_root_dir: "outputs"
